### ISSUE TITLE
create a constants.py

### ISSUE THREAD

**Issue by yashtandon** [yashtandon/TestHack#3]
window_width = 'WINDOWWIDTH'
window_height = 'WINDOWHEIGHT'
board_width  = 'BOARDWIDTH'
board_height = 'BOARDHEIGHT'
text_color = 'TEXTCOLOR'
text_bg_color_1 = 'TEXTBGCOLOR1'
text_bg_color_2 = 'TEXTBGCOLOR2'

**Comment by sculley** [comment]
@yashtandon - can you assign this to me please?
